[package]
name = "sig_viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.99"
byteorder = "1.5.0"
num-complex = "0.4.6"
polars = "0.50.0"
serde = "1.0.224"
serde_json = "1.0.145"
